# Generated by Django 3.2.25 on 2024-06-25 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(auto_now_add=True, verbose_name='Inserimento')),
                ('ts', models.DateTimeField(auto_now=True, verbose_name='Ultima Modifica')),
                ('is_attivo', models.BooleanField(default=True, verbose_name="E' Attivo?")),
                ('codice', models.CharField(max_length=128, unique=True)),
                ('nome', models.CharField(max_length=1024)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Prodotto a Catalogo',
                'verbose_name_plural': 'Prodotti a Catalogo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoProdotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(auto_now_add=True, verbose_name='Inserimento')),
                ('ts', models.DateTimeField(auto_now=True, verbose_name='Ultima Modifica')),
                ('azione', models.CharField(choices=[('prelievo', 'Prelievo'), ('deposito', 'Deposito')], default='deposito', max_length=128)),
                ('quantita', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.prodotto')),
            ],
            options={
                'verbose_name': 'Movimento Prodotto',
                'verbose_name_plural': 'Movimento Prodotti',
                'ordering': ['-ts'],
            },
        ),
    ]
